services:
  web:
    build: .
    ports:
      - "5000:5000"

  db:
    image: "postgres:18.0-alpine3.22"
    environment:
      POSTGRES_USER: 11cloud2
      POSTGRES_DB: 11cloud2_db
      POSTGRES_PASSWORD: zeroZEROzeroZERO
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db_data:
